chat/urls.py
from django.urls import path

from chat.views import (
    MessageCreateView,
    MessageDeleteView,
    ChatCreateView
)

app_name = "chat"
urlpatterns = [
    path(
        "message/<int:pk_author>/<int:pk_task>/",
        MessageCreateView.as_view(),
        name="message_create",
    ),
    path(
        "message/<int:message_pk>/<int:task_pk>/message_delete/",
        MessageDeleteView.as_view(),
        name="message_delete",
    ),
    path("chat/", ChatCreateView.as_view(), name="chat_create"),
]

executor/urls.py
from django.urls import path

from executor.views.project_views import (
    ProjectListView,
    ProjectCreateView,
    ProjectDeleteView,
    ProjectUpdateView,
    ProjectTeamDeleteView,
    ProjectTaskDeleteView,
)
from executor.views.team_views import (
    TeamListView,
    TeamCreateView,
    TeamUpdateView,
    TeamDeleteView,
    TeamTaskDeleteView,
    TeamMemberDeleteView,
    TeamTaskAddView,
    TeamMemberAddView,
)
from executor.views.worker_views import (
    WorkerListView,
    WorkerDetailView,
    WorkerDeleteView,
    WorkerUpdateView,
    WorkerCreateView,
    WorkerTaskAddView,
    WorkerTaskDeleteView,
)

app_name = "executor"
urlpatterns = [
    path("workers/", WorkerListView.as_view(), name="worker_list"),
    path(
        "workers/<int:pk>/", WorkerDetailView.as_view(), name="worker_detail"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker_delete",
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker_update",
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker_create"),
    path(
        "workers/<int:pk>/worker_task_add/",
        WorkerTaskAddView.as_view(),
        name="worker_task_add",
    ),
    path(
        "workers/<int:worker_pk>/<int:task_pk>/task_delete/",
        WorkerTaskDeleteView.as_view(),
        name="worker_task_delete",
    ),
    path("teams/", TeamListView.as_view(), name="team_list"),
    path("teams/create/", TeamCreateView.as_view(), name="team_create"),
    path(
        "teams/<int:pk>/update/", TeamUpdateView.as_view(), name="team_update"
    ),
    path(
        "teams/<int:pk>/delete/", TeamDeleteView.as_view(), name="team_delete"
    ),
    path(
        "teams/<int:team_pk>/<int:task_pk>/task_delete/",
        TeamTaskDeleteView.as_view(),
        name="team_task_delete",
    ),
    path(
        "teams/<int:team_pk>/<int:member_pk>/member_delete/",
        TeamMemberDeleteView.as_view(),
        name="team_member_delete",
    ),
    path(
        "teams/<int:pk>/team_task_add/",
        TeamTaskAddView.as_view(),
        name="team_task_add",
    ),
    path(
        "teams/<int:pk>/team_member_add/",
        TeamMemberAddView.as_view(),
        name="team_member_add",
    ),
    path("projects/", ProjectListView.as_view(), name="project_list"),
    path(
        "projects/create/", ProjectCreateView.as_view(), name="project_create"
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="project_delete",
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project_update",
    ),
    path(
        "projects/<int:project_pk>/<int:team_pk>/task_delete/",
        ProjectTeamDeleteView.as_view(),
        name="project_team_delete",
    ),
    path(
        "projects/<int:project_pk>/<int:task_pk>/member_delete/",
        ProjectTaskDeleteView.as_view(),
        name="project_task_delete",
    ),
]

it_company_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from chat.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", index, name="index"),
    path(
        "task/",
        include("task.urls", namespace="task"),
    ),
    path(
        "executor/",
        include("executor.urls", namespace="executor"),
    ),
    path(
        "chat/",
        include("chat.urls", namespace="chat"),
    ),
    path("accounts/", include("django.contrib.auth.urls")),
]

executor/views/project_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from executor.forms import ProjectSearchForm, ProjectForm
from executor.models import Project, Task
from utils.mixins import SearchMixin, ModelDeleteMixin


class ProjectListView(LoginRequiredMixin, SearchMixin, generic.ListView):
    model = Project
    paginate_by = 4
    queryset = Project.objects.select_related("team").prefetch_related("task")
    template_name = "task_manager/project/project_list.html"
    search_form_class = ProjectSearchForm
    search_fields = ["name"]


class ProjectCreateView(LoginRequiredMixin, generic.CreateView):
    model = Project
    form_class = ProjectForm
    template_name = "task_manager/project/project_form.html"
    success_url = reverse_lazy("executor:project_list")


class ProjectUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = "task_manager/project/project_form.html"


class ProjectDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Project
    template_name = "task_manager/project/project_delete.html"
    success_url = reverse_lazy("executor:project_list")


class ProjectTaskDeleteView(
    LoginRequiredMixin, ModelDeleteMixin, generic.UpdateView
):
    def get(self, request, *args, **kwargs):
        project_id = kwargs.get("project_pk")
        self.remove_object(
            project_id, kwargs.get("task_pk"), "task", Project, Task
        )
        return HttpResponseRedirect(self.get_success_url())


class ProjectTeamDeleteView(
    LoginRequiredMixin, ModelDeleteMixin, generic.UpdateView
):
    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs.get("project_pk"))
        project.team = None
        project.save()
        return HttpResponseRedirect(self.get_success_url())

templates/task_manager/project/project_delete.html
{% extends "layouts/base.html" %}
{% block content %}
	<h2>Are you sure you want to delete project "{{ project.name }}"?</h2>
  {% include "includes/confirm_delete_form.html"%}
{% endblock %}

templates/task_manager/project/project_form.html
{% extends "layouts/base.html" %}
{% block content %}
  <h2 class="text-center">{{ object|yesno:"Update,Create" }} project:</h2>
  {% include "includes/form.html" %}
{% endblock %}

templates/task_manager/project/project_list.html
{% extends "layouts/base.html" %}
{% block content %}
  <div>
    <h2 class="text-center">Project list:</h2>
    <hr>
    <div>
      {% include "includes/search_form.html" %}
      <a href="{% url 'executor:project_create' %}" class="btn btn-primary">Create project</a>
    </div>
    <table class="table">
      <tr>
        <td>ID</td>
        <td>Name</td>
        <td>Description</td>
        <td>Deadline</td>
        <td>Task</td>
        <td>Team</td>
        <td>Edit</td>
        <td></td>
      </tr>
      {% for project in project_list %}
        <tr class="text-white">
          <td>{{ project.id }}</td>
          <td>{{ project.name }}</td>
          <td>{{ project.description }}</td>
          <td>
            {% if project.deadline %}
              {{ project.deadline }}
            {% endif %}
          </td>
          <td>
            {% for task in project.task.all %}
              {{ task }}<a href="{% url 'executor:project_task_delete' project.pk task.pk %}" class="m-2"
                           title="remove a task"
                           data-bs-toggle="tooltip">❌</a><br>
            {% endfor %}
          </td>
          <td>
            {% if project.team %}
              <a href="{% url 'executor:team_list' %}">{{ project.team }}</a>
              <a href="{% url 'executor:project_team_delete' project.pk project.team.pk %}" class="m-2"
                 title="remove a team"
                 data-bs-toggle="tooltip">❌</a><br>
            {% endif %}
          </td>
          <td>
            <a href="{% url 'executor:project_update' project.id %}">✏️</a>
          </td>
          <td><a href="{% url 'executor:project_delete' project.id %}" class="btn btn-danger btn-sm">Delete</a></td>
        </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}