chat/urls.py
from django.urls import path

from chat.views import (
    MessageCreateView,
    MessageDeleteView,
    ChatCreateView
)

app_name = "chat"
urlpatterns = [
    path(
        "message/<int:pk_author>/<int:pk_task>/",
        MessageCreateView.as_view(),
        name="message_create",
    ),
    path(
        "message/<int:message_pk>/<int:task_pk>/message_delete/",
        MessageDeleteView.as_view(),
        name="message_delete",
    ),
    path("chat/", ChatCreateView.as_view(), name="chat_create"),
]

executor/urls.py
from django.urls import path

from executor.views.project_views import (
    ProjectListView,
    ProjectCreateView,
    ProjectDeleteView,
    ProjectUpdateView,
    ProjectTeamDeleteView,
    ProjectTaskDeleteView,
)
from executor.views.team_views import (
    TeamListView,
    TeamCreateView,
    TeamUpdateView,
    TeamDeleteView,
    TeamTaskDeleteView,
    TeamMemberDeleteView,
    TeamTaskAddView,
    TeamMemberAddView,
)
from executor.views.worker_views import (
    WorkerListView,
    WorkerDetailView,
    WorkerDeleteView,
    WorkerUpdateView,
    WorkerCreateView,
    WorkerTaskAddView,
    WorkerTaskDeleteView,
)

app_name = "executor"
urlpatterns = [
    path("workers/", WorkerListView.as_view(), name="worker_list"),
    path(
        "workers/<int:pk>/", WorkerDetailView.as_view(), name="worker_detail"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker_delete",
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker_update",
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker_create"),
    path(
        "workers/<int:pk>/worker_task_add/",
        WorkerTaskAddView.as_view(),
        name="worker_task_add",
    ),
    path(
        "workers/<int:worker_pk>/<int:task_pk>/task_delete/",
        WorkerTaskDeleteView.as_view(),
        name="worker_task_delete",
    ),
    path("teams/", TeamListView.as_view(), name="team_list"),
    path("teams/create/", TeamCreateView.as_view(), name="team_create"),
    path(
        "teams/<int:pk>/update/", TeamUpdateView.as_view(), name="team_update"
    ),
    path(
        "teams/<int:pk>/delete/", TeamDeleteView.as_view(), name="team_delete"
    ),
    path(
        "teams/<int:team_pk>/<int:task_pk>/task_delete/",
        TeamTaskDeleteView.as_view(),
        name="team_task_delete",
    ),
    path(
        "teams/<int:team_pk>/<int:member_pk>/member_delete/",
        TeamMemberDeleteView.as_view(),
        name="team_member_delete",
    ),
    path(
        "teams/<int:pk>/team_task_add/",
        TeamTaskAddView.as_view(),
        name="team_task_add",
    ),
    path(
        "teams/<int:pk>/team_member_add/",
        TeamMemberAddView.as_view(),
        name="team_member_add",
    ),
    path("projects/", ProjectListView.as_view(), name="project_list"),
    path(
        "projects/create/", ProjectCreateView.as_view(), name="project_create"
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="project_delete",
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project_update",
    ),
    path(
        "projects/<int:project_pk>/<int:team_pk>/task_delete/",
        ProjectTeamDeleteView.as_view(),
        name="project_team_delete",
    ),
    path(
        "projects/<int:project_pk>/<int:task_pk>/member_delete/",
        ProjectTaskDeleteView.as_view(),
        name="project_task_delete",
    ),
]

it_company_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from chat.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", index, name="index"),
    path(
        "task/",
        include("task.urls", namespace="task"),
    ),
    path(
        "executor/",
        include("executor.urls", namespace="executor"),
    ),
    path(
        "chat/",
        include("chat.urls", namespace="chat"),
    ),
    path("accounts/", include("django.contrib.auth.urls")),
]

task/urls.py
from django.urls import path

from task.views import (
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskDeleteView,
    TaskUpdateView,
    TaskStatusUpdateView,
    TagListView,
    TagCreateView,
    TagDeleteView,
    TagUpdateView
)

app_name = "task"
urlpatterns = [

    path("tasks/", TaskListView.as_view(), name="task_list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task_create"),
    path(
        "tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"
    ),
    path(
        "tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task_update"
    ),
    path(
        "tasks/<int:pk>/complete/",
        TaskStatusUpdateView.as_view(),
        name="task_status_update",
    ),

    path("tags/", TagListView.as_view(), name="tag_list"),
    path("tags/create/", TagCreateView.as_view(), name="tag_create"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag_update"),
]

templates/includes/confirm_delete_form.html
<h6 class="opacity-5">*Please note, all data about this object will be deleted permanently.</h6>
<div class="d-flex">
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger m-lg-5">
  </form>
  <button
      onclick="history.back()"
      class="btn btn-info m-lg-5">Cancel
  </button>
</div>

templates/includes/form.html
{% load crispy_forms_filters %}
<div class="container">
  <form
      action=""
      method="post"
      class="container border-radius-xl mr-lg-10 ml-lg-10">
    {% csrf_token %}
    <div>
      {{ form|crispy }}
    </div>
    <input type="submit" value="Submit" class="btn btn-success m-4">
  </form>
</div>

templates/includes/navigation.html
<div class="container position-sticky z-index-sticky top-0 opacity-7">
  <div class="row">
    <div class="col-12">
      <nav
          class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="btn btn-sm bg-gradient-info  mb-0 me-1 mt-2 mt-md-0" href="/" rel="tooltip"
             title="Designed and Coded by Creative Tim" data-placement="bottom">
            Home
          </a>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-auto">
              <li class="nav-item my-auto ms-3 ms-lg-0">
                <a href="{% url 'executor:project_create' %}"
                   class="btn btn-sm bg-gradient-success  mb-0 me-1 mt-2 mt-md-0">Create Project</a>
              </li>
              <li class="nav-item my-auto ms-3 ms-lg-0">
                <a href="{% url 'executor:team_create' %}"
                   class="btn btn-sm bg-gradient-success  mb-0 me-1 mt-2 mt-md-0">Create Team</a>
              </li>
              <li class="nav-item my-auto ms-3 ms-lg-0">
                <a href="{% url 'task:task_create' %}"
                   class="btn btn-sm bg-gradient-success  mb-0 me-1 mt-2 mt-md-0">Create task</a>
              </li>
              <li class="nav-item my-auto ms-3 ms-lg-0">
                <a href="{% url 'task:tag_create' %}"
                   class="btn btn-sm bg-gradient-success  mb-0 me-1 mt-2 mt-md-0">Create tag</a>
              </li>
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuDocs"
                   data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="material-icons opacity-6 me-2 text-md">article</i>
                  Menu
                  <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                </a>
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-animation dropdown-md dropdown-md-responsive mt-0 mt-lg-3 p-3 border-radius-lg list-group d-none d-lg-block"
                    aria-labelledby="dropdownMenuDocs">
                  <li class="nav-item list-group-item border-0 p-0">
                    <a class="dropdown-item py-2 ps-3 border-radius-md"
                       href="{% url 'executor:project_list' %}">
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">
                        Projects</h6>
                      <span class="text-sm"> </span>
                    </a>
                  </li>
                  <li class="nav-item list-group-item border-0 p-0">
                    <a class="dropdown-item py-2 ps-3 border-radius-md"
                       href="{% url 'task:task_list' %}">
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">
                        Tasks</h6>
                      <span class="text-sm"> </span>
                    </a>
                  </li>

                  <li class="nav-item list-group-item border-0 p-0">
                    <a class="dropdown-item py-2 ps-3 border-radius-md"
                       href="{% url 'task:tag_list' %}">
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">
                        Tags</h6>
                      <span class="text-sm"> </span>
                    </a>
                  </li>

                  <li class="nav-item list-group-item border-0 p-0">
                    <a class="dropdown-item py-2 ps-3 border-radius-md"
                       href="{% url 'executor:team_list' %}">
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">
                        Teams</h6>
                      <span class="text-sm"> </span>
                    </a>
                  </li>

                  <li class="nav-item list-group-item border-0 p-0">
                    <a class="dropdown-item py-2 ps-3 border-radius-md"
                       href="{% url 'executor:worker_list' %}">
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">
                        Workers</h6>
                      <span class="text-sm"> </span>
                    </a>
                  </li>
                </ul>
                {% if user.is_authenticated %}
                  <li class="nav-item my-auto ms-3 ms-lg-0">
                    <a href="{% url 'executor:worker_detail' user.id %}"
                       class="btn btn-sm  bg-gradient-primary  mb-0 me-1 mt-2 mt-md-0"
                       title="Edit profile"
                       data-bs-toggle="tooltip">{{ user.username }}</a>
                  </li>
                  <li class="nav-item ms-lg-auto">
                    <form action="{% url 'logout' %}?next={{ request.path }}" method="post" style="display: none;"
                          id="logout-form">
                      {% csrf_token %}
                    </form>
                    <a class="nav-link nav-link-icon me-2" href="#"
                       onclick="document.getElementById('logout-form').submit();">
                      <i class="fa fa-sign-out me-1"></i>
                      <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                         data-bs-placement="bottom" title="Sign OUT">Logout</p>
                    </a>
                  </li>
                {% else %}
                  <li class="nav-item ms-lg-auto">
                    <form action="{% url 'login' %}?next={{ request.path }}" method="post" style="display: none;"
                          id="login-form">
                      {% csrf_token %}
                    </form>
                    <a class="nav-link nav-link-icon me-2" href="#"
                       onclick="document.getElementById('login-form').submit();">
                      <i class="fa fa-sign-in me-1"></i>
                      <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                         data-bs-placement="bottom" title="Sign IN">Login</p>
                    </a>
                  </li>
                {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% load query_transform %}
{% if is_paginated %}
  <div class="pagination-container">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li>
          <a
              class="btn btn-primary p-lg-2 m-1"
              href="?{% query_transform request page=page_obj.previous_page_number %}">Prev
          </a>
        </li>
      {% endif %}
      <li class="page-item-active"><span
          class="page-link border-radius-lg m-1">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
      </li>
      {% if page_obj.has_next %}
        <li>
          <a
              class="btn btn-primary p-lg-2 m-1"
              href="?page={{ page_obj.next_page_number }}">Next
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
{% endif %}

templates/includes/scripts.html
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>
<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
<script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>
<script type="text/javascript">
    if (document.getElementById('state1')) {
        const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
        if (!countUp.error) {
            countUp.start();
        } else {
            console.error(countUp.error);
        }
    }
    if (document.getElementById('state2')) {
        const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
        if (!countUp1.error) {
            countUp1.start();
        } else {
            console.error(countUp1.error);
        }
    }
    if (document.getElementById('state3')) {
        const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
        if (!countUp2.error) {
            countUp2.start();
        } else {
            console.error(countUp2.error);
        }
    }
    if (document.getElementById('state4')) {
        const countUp2 = new CountUp('state4', document.getElementById("state4").getAttribute("countTo"));
        if (!countUp2.error) {
            countUp2.start();
        } else {
            console.error(countUp2.error);
        }
    }
</script>

templates/includes/search_form.html
{% load crispy_forms_filters %}
<form action="" method="get">
  <div class="d-flex align-items-center justify-content-between w-25">
    <div class="w-75">
      {{ search_form|crispy }}
    </div>
    <input type="submit" value=" 🔍 " class="btn btn-light">
  </div>
</form>