chat/urls.py
from django.urls import path

from chat.views import (
    MessageCreateView,
    MessageDeleteView,
    ChatCreateView
)

app_name = "chat"
urlpatterns = [
    path(
        "message/<int:pk_author>/<int:pk_task>/",
        MessageCreateView.as_view(),
        name="message_create",
    ),
    path(
        "message/<int:message_pk>/<int:task_pk>/message_delete/",
        MessageDeleteView.as_view(),
        name="message_delete",
    ),
    path("chat/", ChatCreateView.as_view(), name="chat_create"),
]

executor/urls.py
from django.urls import path

from executor.views.project_views import (
    ProjectListView,
    ProjectCreateView,
    ProjectDeleteView,
    ProjectUpdateView,
    ProjectTeamDeleteView,
    ProjectTaskDeleteView,
)
from executor.views.team_views import (
    TeamListView,
    TeamCreateView,
    TeamUpdateView,
    TeamDeleteView,
    TeamTaskDeleteView,
    TeamMemberDeleteView,
    TeamTaskAddView,
    TeamMemberAddView,
)
from executor.views.worker_views import (
    WorkerListView,
    WorkerDetailView,
    WorkerDeleteView,
    WorkerUpdateView,
    WorkerCreateView,
    WorkerTaskAddView,
    WorkerTaskDeleteView,
)

app_name = "executor"
urlpatterns = [
    path("workers/", WorkerListView.as_view(), name="worker_list"),
    path(
        "workers/<int:pk>/", WorkerDetailView.as_view(), name="worker_detail"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker_delete",
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker_update",
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker_create"),
    path(
        "workers/<int:pk>/worker_task_add/",
        WorkerTaskAddView.as_view(),
        name="worker_task_add",
    ),
    path(
        "workers/<int:worker_pk>/<int:task_pk>/task_delete/",
        WorkerTaskDeleteView.as_view(),
        name="worker_task_delete",
    ),
    path("teams/", TeamListView.as_view(), name="team_list"),
    path("teams/create/", TeamCreateView.as_view(), name="team_create"),
    path(
        "teams/<int:pk>/update/", TeamUpdateView.as_view(), name="team_update"
    ),
    path(
        "teams/<int:pk>/delete/", TeamDeleteView.as_view(), name="team_delete"
    ),
    path(
        "teams/<int:team_pk>/<int:task_pk>/task_delete/",
        TeamTaskDeleteView.as_view(),
        name="team_task_delete",
    ),
    path(
        "teams/<int:team_pk>/<int:member_pk>/member_delete/",
        TeamMemberDeleteView.as_view(),
        name="team_member_delete",
    ),
    path(
        "teams/<int:pk>/team_task_add/",
        TeamTaskAddView.as_view(),
        name="team_task_add",
    ),
    path(
        "teams/<int:pk>/team_member_add/",
        TeamMemberAddView.as_view(),
        name="team_member_add",
    ),
    path("projects/", ProjectListView.as_view(), name="project_list"),
    path(
        "projects/create/", ProjectCreateView.as_view(), name="project_create"
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="project_delete",
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project_update",
    ),
    path(
        "projects/<int:project_pk>/<int:team_pk>/task_delete/",
        ProjectTeamDeleteView.as_view(),
        name="project_team_delete",
    ),
    path(
        "projects/<int:project_pk>/<int:task_pk>/member_delete/",
        ProjectTaskDeleteView.as_view(),
        name="project_task_delete",
    ),
]

it_company_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from chat.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", index, name="index"),
    path(
        "task/",
        include("task.urls", namespace="task"),
    ),
    path(
        "executor/",
        include("executor.urls", namespace="executor"),
    ),
    path(
        "chat/",
        include("chat.urls", namespace="chat"),
    ),
    path("accounts/", include("django.contrib.auth.urls")),
]

task/urls.py
from django.urls import path

from task.views import (
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskDeleteView,
    TaskUpdateView,
    TaskStatusUpdateView,
    TagListView,
    TagCreateView,
    TagDeleteView,
    TagUpdateView
)

app_name = "task"
urlpatterns = [

    path("tasks/", TaskListView.as_view(), name="task_list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task_create"),
    path(
        "tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"
    ),
    path(
        "tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task_update"
    ),
    path(
        "tasks/<int:pk>/complete/",
        TaskStatusUpdateView.as_view(),
        name="task_status_update",
    ),

    path("tags/", TagListView.as_view(), name="tag_list"),
    path("tags/create/", TagCreateView.as_view(), name="tag_create"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag_update"),
]

executor/views/team_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from executor.forms import (
    TeamSearchForm,
    TeamCreateForm,
    TeamTaskAddForm,
    TeamMemberAddForm,
)
from executor.models import Team, Task, Worker
from utils.mixins import SearchMixin, ModelDeleteMixin


class TeamListView(LoginRequiredMixin, SearchMixin, generic.ListView):
    model = Team
    paginate_by = 4
    queryset = Team.objects.all().prefetch_related(
        "member", "task", "projects"
    )
    template_name = "task_manager/team/team_list.html"
    search_form_class = TeamSearchForm
    search_fields = ["name"]


class TeamCreateView(LoginRequiredMixin, generic.CreateView):
    model = Team
    form_class = TeamCreateForm
    template_name = "task_manager/task/task_form.html"
    success_url = reverse_lazy("executor:team_list")


class TeamUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Team
    fields = "__all__"
    template_name = "task_manager/team/team_form.html"


class TeamDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Team
    success_url = reverse_lazy("executor:team_list")
    template_name = "task_manager/team/team_delete.html"


class TeamTaskDeleteView(
    LoginRequiredMixin, ModelDeleteMixin, generic.UpdateView
):
    def get(self, request, *args, **kwargs):
        team_id = kwargs.get("team_pk")
        self.remove_object(team_id, kwargs.get("task_pk"), "task", Team, Task)
        return HttpResponseRedirect(reverse_lazy("executor:team_list"))


class TeamMemberDeleteView(
    LoginRequiredMixin, ModelDeleteMixin, generic.UpdateView
):
    def get(self, request, *args, **kwargs):
        team_id = kwargs.get("team_pk")
        self.remove_object(
            team_id, kwargs.get("member_pk"), "member", Team, Worker
        )
        return HttpResponseRedirect(reverse_lazy("executor:team_list"))


class TeamTaskAddView(LoginRequiredMixin, generic.UpdateView):
    model = Team
    form_class = TeamTaskAddForm
    template_name = "task_manager/team/team_form.html"


class TeamMemberAddView(LoginRequiredMixin, generic.UpdateView):
    model = Team
    form_class = TeamMemberAddForm
    template_name = "task_manager/team/team_form.html"

templates/task_manager/team/team_delete.html
{% extends "layouts/base.html" %}
{% block content %}
	<h2>Are you sure you want to delete team "{{ team.name }}"?</h2>
  {% include "includes/confirm_delete_form.html"%}
{% endblock %}

templates/task_manager/team/team_form.html
{% extends "layouts/base.html" %}
{% block content %}
  <h2 class="text-center">{{ object|yesno:"Update,Create" }} team:</h2>
  {% include "includes/form.html" %}
{% endblock %}

templates/task_manager/team/team_list.html
{% extends "layouts/base.html" %}
{% block content %}
  <div>
    <h1>
      Teams:
    </h1>
    <div class="">
      {% include "includes/search_form.html" %}
      <a href="{% url 'executor:team_create' %}" class="btn btn-success btn-sm">+ Add team</a>
    </div>
    <table class="table">
      <tr>
        <td>ID</td>
        <td></td>
        <td>Name</td>
        <td>Project</td>
        <td>Tasks</td>
        <td></td>
        <td>Members</td>
        <td></td>
      </tr>
      {% for team in team_list %}
        <tr>
          <td>{{ team.pk }}</td>
          <td><a href="{% url 'executor:team_delete' team.id %}" class="btn btn-danger btn-sm"
                 title="Delete Team"
                 data-bs-toggle="tooltip">🗑️</a></td>
          <td>
            <h3>{{ team.name }}</h3>
          </td>
          <td>
            {% for project in team.projects.all %}
              {{ project.name }}<br>
            {% endfor %}

          </td>
          <td>
            {% for task in team.task.all %}
              <div class="d-flex mr-lg-1">
                {% if task.is_completed == True %}
                  <form
                      action="{% url 'task:task_status_update' task.id %}?next=/executor/teams/"
                      method="post">
                    {% csrf_token %}
                    <input type="submit" value="✅" class="btn p-0" name="status">
                  </form>
                {% else %}
                  <form
                      action="{% url 'task:task_status_update' task.id %}?next=/executor/teams"
                      method="post">
                    {% csrf_token %}
                    <input type="submit" value="🔄" class="btn p-0" name="status">
                  </form>
                {% endif %}
                <a href="{% url 'task:task_detail' task.pk %}">{{ task }}</a>
                <a href="{% url 'executor:team_task_delete' team.pk task.id %}"
                   title="remove a task"
                   data-bs-toggle="tooltip">❌</a><br>
              </div>
            {% endfor %}
          </td>
          <td><a href="{% url 'executor:team_task_add' team.id %}" class="btn btn-sm btn-success">Add task</a></td>
          <td class="text-white">

            {% for member in team.member.all %}
              <a href="{% url 'executor:worker_detail' member.pk %}">{{ member }}</a>
              <a href="{% url 'executor:team_member_delete' team.pk member.id %}" class="m-2"
                 title="remove a team member"
                 data-bs-toggle="tooltip">❌</a><br>
            {% endfor %}
          </td>
          <td><a href="{% url 'executor:team_member_add' team.id %}" class="btn btn-sm btn-warning ">Add
            member</a></td>
        </tr>
      {% endfor %}
    </table>

  </div>
{% endblock %} 