chat/urls.py
from django.urls import path

from chat.views import (
    MessageCreateView,
    MessageDeleteView,
    ChatCreateView
)

app_name = "chat"
urlpatterns = [
    path(
        "message/<int:pk_author>/<int:pk_task>/",
        MessageCreateView.as_view(),
        name="message_create",
    ),
    path(
        "message/<int:message_pk>/<int:task_pk>/message_delete/",
        MessageDeleteView.as_view(),
        name="message_delete",
    ),
    path("chat/", ChatCreateView.as_view(), name="chat_create"),
]

executor/urls.py
from django.urls import path

from executor.views.project_views import (
    ProjectListView,
    ProjectCreateView,
    ProjectDeleteView,
    ProjectUpdateView,
    ProjectTeamDeleteView,
    ProjectTaskDeleteView,
)
from executor.views.team_views import (
    TeamListView,
    TeamCreateView,
    TeamUpdateView,
    TeamDeleteView,
    TeamTaskDeleteView,
    TeamMemberDeleteView,
    TeamTaskAddView,
    TeamMemberAddView,
)
from executor.views.worker_views import (
    WorkerListView,
    WorkerDetailView,
    WorkerDeleteView,
    WorkerUpdateView,
    WorkerCreateView,
    WorkerTaskAddView,
    WorkerTaskDeleteView,
)

app_name = "executor"
urlpatterns = [
    path("workers/", WorkerListView.as_view(), name="worker_list"),
    path(
        "workers/<int:pk>/", WorkerDetailView.as_view(), name="worker_detail"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker_delete",
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker_update",
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker_create"),
    path(
        "workers/<int:pk>/worker_task_add/",
        WorkerTaskAddView.as_view(),
        name="worker_task_add",
    ),
    path(
        "workers/<int:worker_pk>/<int:task_pk>/task_delete/",
        WorkerTaskDeleteView.as_view(),
        name="worker_task_delete",
    ),
    path("teams/", TeamListView.as_view(), name="team_list"),
    path("teams/create/", TeamCreateView.as_view(), name="team_create"),
    path(
        "teams/<int:pk>/update/", TeamUpdateView.as_view(), name="team_update"
    ),
    path(
        "teams/<int:pk>/delete/", TeamDeleteView.as_view(), name="team_delete"
    ),
    path(
        "teams/<int:team_pk>/<int:task_pk>/task_delete/",
        TeamTaskDeleteView.as_view(),
        name="team_task_delete",
    ),
    path(
        "teams/<int:team_pk>/<int:member_pk>/member_delete/",
        TeamMemberDeleteView.as_view(),
        name="team_member_delete",
    ),
    path(
        "teams/<int:pk>/team_task_add/",
        TeamTaskAddView.as_view(),
        name="team_task_add",
    ),
    path(
        "teams/<int:pk>/team_member_add/",
        TeamMemberAddView.as_view(),
        name="team_member_add",
    ),
    path("projects/", ProjectListView.as_view(), name="project_list"),
    path(
        "projects/create/", ProjectCreateView.as_view(), name="project_create"
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="project_delete",
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project_update",
    ),
    path(
        "projects/<int:project_pk>/<int:team_pk>/task_delete/",
        ProjectTeamDeleteView.as_view(),
        name="project_team_delete",
    ),
    path(
        "projects/<int:project_pk>/<int:task_pk>/member_delete/",
        ProjectTaskDeleteView.as_view(),
        name="project_task_delete",
    ),
]

it_company_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from chat.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", index, name="index"),
    path(
        "task/",
        include("task.urls", namespace="task"),
    ),
    path(
        "executor/",
        include("executor.urls", namespace="executor"),
    ),
    path(
        "chat/",
        include("chat.urls", namespace="chat"),
    ),
    path("accounts/", include("django.contrib.auth.urls")),
]

task/urls.py
from django.urls import path

from task.views import (
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskDeleteView,
    TaskUpdateView,
    TaskStatusUpdateView,
    TagListView,
    TagCreateView,
    TagDeleteView,
    TagUpdateView
)

app_name = "task"
urlpatterns = [

    path("tasks/", TaskListView.as_view(), name="task_list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task_create"),
    path(
        "tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"
    ),
    path(
        "tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task_update"
    ),
    path(
        "tasks/<int:pk>/complete/",
        TaskStatusUpdateView.as_view(),
        name="task_status_update",
    ),

    path("tags/", TagListView.as_view(), name="tag_list"),
    path("tags/create/", TagCreateView.as_view(), name="tag_create"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag_update"),
]

executor/views/worker_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from executor.forms import (
    WorkerSearchForm,
    WorkerCreateForm,
    WorkerUpdateForm,
    WorkerTaskAddForm,
)
from executor.models import Worker, Task
from utils.mixins import ModelDeleteMixin


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 4
    queryset = Worker.objects.select_related("position")
    template_name = "task_manager/worker/worker_list.html"

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(WorkerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get(key="username", default="")
        context["search_form"] = WorkerSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self) -> QuerySet:
        queryset = Worker.objects.select_related("position")
        username = self.request.GET.get("username", "")
        if username:
            return queryset.filter(username__icontains=username)
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    template_name = "task_manager/worker/worker_detail.html"

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(WorkerDetailView, self).get_context_data(**kwargs)
        worker = self.get_object()
        tasks = Task.objects.filter(assignees=worker)
        context["tasks"] = tasks
        return context


class WorkerCreateView(generic.CreateView):
    model = Worker
    form_class = WorkerCreateForm
    template_name = "task_manager/worker/worker_form.html"


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerUpdateForm
    template_name = "task_manager/worker/worker_form.html"
    success_url = reverse_lazy("executor:worker_list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    template_name = "task_manager/worker/worker_delete.html"
    success_url = reverse_lazy("executor:worker_list")


class WorkerTaskDeleteView(
    LoginRequiredMixin, ModelDeleteMixin, generic.UpdateView
):
    def get(self, request, *args, **kwargs):
        worker_id = kwargs.get("worker_pk")
        task_id = kwargs.get("task_pk")
        self.remove_object(task_id, worker_id, "assignees", Task, Worker)
        return HttpResponseRedirect(
            reverse_lazy("executor:worker_detail", args=[worker_id])
        )


class WorkerTaskAddView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerTaskAddForm
    template_name = "task_manager/worker/worker_form.html"

    def form_valid(self, form):
        worker = form.save(commit=False)
        tasks = form.cleaned_data["tasks"]
        for task in tasks:
            task.assignees.add(worker)
            task.save()
        return HttpResponseRedirect(self.get_success_url())

templates/task_manager/worker/worker_delete.html
{% extends "layouts/base.html" %}
{% block content %}
	<h2>Are you sure you want to delete worker "{{ worker.first_name }} {{ worker.last_name }}"?</h2>
  {% include "includes/confirm_delete_form.html"%}
{% endblock %}

templates/task_manager/worker/worker_detail.html
{% extends "layouts/base.html" %}
{% block content %}
  <div class="container d-flex">
    <div>
      <h2>{{ worker.first_name }} {{ worker.last_name }}</h2>
      <hr>
      <a
          href="{% url 'executor:worker_update' worker.id %}"
          class="btn btn-sm btn-info mt-3"
      >Update</a>
      <a href="{% url 'executor:worker_delete' worker.id %}" class="btn btn-sm btn-danger mt-3">Delete</a>
      <hr>
      <h4>position: {{ worker.position }}</h4>
      <hr>
      <h4>{{ worker.email }}</h4>
    </div>
    <div class="container w-50">
      <h3>Tasks:<a href="{% url 'executor:worker_task_add' worker.id %}" class="btn btn-sm btn-success"
                   style="margin-left: 20px">Add task</a></h3>
      {% for task in tasks %}
        <div class="d-flex mr-lg-1">
          {% if task.is_completed == True %}
            <form
                action="{% url 'task:task_status_update' task.id %}?next=/executor/workers/{{ worker.id }}/"
                method="post">
              {% csrf_token %}
              <input type="submit" value="✅" class="btn p-0" name="status">
            </form>
          {% else %}
            <form
                action="{% url 'task:task_status_update' task.id %}?next=/executor/workers/{{ worker.id }}/"
                method="post">
              {% csrf_token %}
              <input type="submit" value="🔄" class="btn p-0" name="status">
            </form>
          {% endif %}
          <a href="{% url 'task:task_detail' task.pk %}" title="Task detail"
             data-bs-toggle="tooltip">{{ task }}</a>
          <a href="{% url 'executor:worker_task_delete' worker.pk task.pk %}" class=""
             title="Remove task from this user"
             data-bs-toggle="tooltip">❌</a><br>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/task_manager/worker/worker_form.html
{% extends "layouts/base.html" %}
{% block content %}
  <h2 class="text-center">{{ object|yesno:"Update,Create" }} worker:</h2>
  {% include "includes/form.html" %}
{% endblock %}

templates/task_manager/worker/worker_list.html
{% extends "layouts/base.html" %}
{% block content %}
  {% include "includes/search_form.html" %}
  <table class="container table border-radius-xl" style="background-color: rgba(220, 220, 220, 0.2);">
    <tr class="text-center">
      <td>ID</td>
      <td>Username</td>
      <td>Name</td>
      <td>Position</td>
      <td>Email</td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    {% for worker in worker_list %}
      <tr class="text-white text-center">
        <td>{{ worker.id }}</td>
        <td>{{ worker.username }}</td>
        <td>{{ worker.first_name }} {{ worker.last_name }}</td>
        <td>{{ worker.position }}</td>
        <td>{{ worker.email }}</td>
        <td><a href="{% url 'executor:worker_detail' worker.id %}" class="btn btn-sm btn-secondary">Detail</a></td>
        <td><a href="{% url 'executor:worker_update' worker.id %}" class="btn btn-sm btn-info">Update</a></td>
        <td>
          {% if worker.id == user.id %}
            <a href="{% url 'executor:worker_delete' worker.id %}" class="btn btn-sm btn-danger">Delete</a>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}